### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PoisonousJohn** [irrationalistic/sublime-xmldocs#1]
please provide license file. I love your plugin, but I can't use it on my work since there's no license

**Comment by irrationalistic** [comment]
I don't know much about licensing, so what is the ideal license to use? I have no qualms with folks using this however they want as long as they aren't selling it as their own work!

**Comment by PoisonousJohn** [comment]
https://help.github.com/articles/open-source-licensing/

i guess it should help. I think MIT license should fit

**Comment by irrationalistic** [comment]
It's actually pretty easy to add this with github. You just create a new file on github.com with the name LICENSE and it brings up a dropdown!
